name: nour_arch
description: "New Mansoura Development Project — University Architecture Showcase."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  video_player: ^2.9.2
  url_launcher: ^6.3.0
  panorama_viewer: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/

  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter_18pt-Bold.ttf
          weight: 700
